#!/usr/bin/env python

import argparse
import os
import re
import sys
import h5py


def get_fast5_dirs(fast5_dir, reference, out_file):
    """Returns the paths to all fast5 files contained in the fastq BAM/SAM file.

    Args:
        fast5_dir (str): The path to the directory where the fast5 files are.
        reference (str): Path to the fastq or BAM/SAM file.
        out_file (File): File to write the fast5 paths contained
        in the fastq file to.

    """
    # get a set of the read ids in the fastq or BAM/SAM file
    read_ids = extract_read_ids(reference)

    # get the absolute path for the fast5 directory
    abs_path = os.path.abspath(os.path.realpath(fast5_dir))

    filepaths = set()
    for root, dirs, files in os.walk(abs_path):  # recursively walk fast5_dir
        for file_ in files:

            if file_.endswith(".fast5"):
                filepath = os.path.join(root, file_)
                
                try:
                    read_id = get_read_id(filepath)
                except IOError:  # file cannot be opened
                    continue

                # if the file is in the fastq file and it has not 
                # already been found...
                if read_id in read_ids and filepath not in filepaths:
                    filepaths.add(filepath)
                    out_file.write(filepath + '\n')

    sys.stderr.write('{} files found.\n'.format(len(filepaths)))


def get_read_group(list_of_names):
    """Extracts the correct group name for the group containing the read_id"""
    for name in list_of_names:
        if re.search(r'Read_\d+$', name):
            return name


def get_read_id(filepath):
    """Extracts the read_id from a given fast5 file.
    If the file cannot be opened, it will be skipped.

    Args:
        filepath (str): Path to the fast5 file.

    Returns:
        read_id (str): The read_id

    """
    group = 'Raw/Reads/'
    try:
        with h5py.File(filepath, 'r') as fast5:
            list_of_names = []

            # get all group names in the Raw/Reads group
            fast5['Raw/Reads'].visit(list_of_names.append)

            # extracts the group name that ends in the pattern 'Read_\d+'
            # where \d+ is any number of digits
            read_group = get_read_group(list_of_names)
            group += read_group

            return fast5[group].attrs['read_id']  # the read_id

    except IOError as err:  # skip file if it cannot be opened
        sys.stderr.write('{} could not be opened. \
            Skipping...\n'.format(filepath))
        raise err


def extract_read_ids(ref_path):
    """Extracts the all the read ids from the fastq file.
    The read_id is the first part of the header and starts with an @

    Args:
        ref_path (str): Path to the fastq or BAM/SAM file to extract
        read_ids from.

    Returns:
        read_ids (set[str]): A set of all the read ids in the fastq file.

    """
    # get the absolute path and the file extension
    ref_path = os.path.abspath(os.path.realpath(ref_path))
    extension = os.path.splitext(ref_path)[1][1:]

    if extension in {'bam', 'sam'}:
        read_ids = get_read_id_sam(ref_path)
    elif extension in {'fq', 'fastq'}:
        read_ids = get_read_id_fastq(ref_path)
    else:
        raise Exception('{} is not a supported file format. Supported file '
                        'types are: .fastq, .sam, and .bam'.format(extension))

    return read_ids


def get_read_id_fastq(ref_path):
    """Extracts the read ids from a fastq file."""
    read_ids = set()
    with open(ref_path, 'r') as ref:
        for line in ref:
            if line.startswith('@'):  # i.e if line is header
                # split the line on spaces, take the first element, remove @
                read_id = line.split(' ')[0].replace('@', '')
                read_ids.add(read_id)

    return read_ids


def get_read_id_sam(ref_path):
    """Extract the read ids from a BAM or SAM file."""
    import pysam

    read_ids = set()
    with pysam.AlignmentFile(ref_path, 'r', ignore_truncation=True) as ref:
        for read in ref:
            # query_name is the query template name
            read_ids.add(read.query_name)

    return read_ids


def main():
    parser = argparse.ArgumentParser(
            description = "Outputs paths of all the fast5 files from a \
            given directory that are contained within a fastq or BAM/SAM file.",
            prog='fast5_in_fastq',
            )

    parser.add_argument(
            "-i", "--fast5_dir",
            help="Directory of fast5 files you want to query. Program will \
            walk recursively through subdirectories.",
            type=str, required=True)

    parser.add_argument(
            "-r", "--reference",
            help="Fastq or BAM/SAM file.",
            required=True)

    parser.add_argument(
            "-o", "--output",
            help="Filename to write fast5 paths to. If nothing is entered, \
            it will write the paths to STDOUT.", 
            default=None)

    args = parser.parse_args()

    # if no output is given, write to stdout
    out_file = args.output or sys.stdout

    get_fast5_dirs(args.fast5_dir, args.reference, out_file)


if __name__ == '__main__':
    main()
